name: 'kubectl-simple'
description: 'The kubectl command line program as a GitHub Action'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}
    - ${{ inputs.config }}
    - ${{ inputs.dryrun }}
    - ${{ inputs.commands }}
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  version:
    description: 'kubectl version, e.g. `v1.21.0`, defaults to latest'
    required: false
    default: latest
  config:
    description: 'kube config data'
    required: true
  dryrun:
    description: 'should --dry-run=client be used, e.g. `dryrun: true`'
    required: false
    default: 'false'
  command:
    description: 'kubectl commands to run, without the kubectl, e.g. `get pods`'
    required: true
